### ISSUE TITLE
[Android] Keyboard visibility value not changing in Kotlin based Flutter apps

### ISSUE THREAD

**Issue by noraibrahimi** [MisterJimson/flutter_keyboard_visibility#5]
I have this code on my initState:
`  @override
  void initState() {
    super.initState();
    KeyboardVisibilityNotification().addNewListener(
      onChange: (bool visible) {
        setState(() {
          _isKeyBoardVisible = visible;
        });
      },
    );}`

The same code is working on IOS.
Package:   flutter_keyboard_visibility: ^0.7.0

**Comment by MisterJimson** [comment]
Does the example project work for you?

**Comment by noraibrahimi** [comment]
Yes the example is working, I also copied the keyboard part of the example on my project and there it isn't working.
Can it be that I am using a keyboard listener in more than one part of the project, but still in IOS it's working.

**Comment by MisterJimson** [comment]
That could possibly be the issue. I'm not sure. If you can add any other detail here that helps me reproduce the issue I can investigate.

**Comment by noraibrahimi** [comment]
I tried this in a demo project:
[https://pastebin.com/hfkbzzdP](url)

Package:   flutter_keyboard_visibility: ^0.7.0

**Comment by MisterJimson** [comment]
I tried your code. Worked fine for me. Both the UI and print statement are updating.

https://imgur.com/a/nspOZyh

Could it be a specific Android version or device? Which are you using? I'm using an API 29 Android emulator.

**Comment by noraibrahimi** [comment]
I ran it on two real devices: Samsung A7 and A5
And also in an emulator and on all it didn't work. 
Here are some screens with keyboard up and down:

![image](https://user-images.githubusercontent.com/33460814/78380868-d5e08880-75d4-11ea-9d67-0f661fe309c6.png)
![image](https://user-images.githubusercontent.com/33460814/78380902-e133b400-75d4-11ea-83fb-2683ba729864.png)

**Comment by MisterJimson** [comment]
Which Android version of the emulator?

**Comment by henk789** [comment]
I experience this issue as well on a physical device as well as the emulator (API 29 Android).

The provided example using a Java Android project works as expected. However, recreating the Android project using Kotlin produces the issue.

I tested and reproduced this multiple times in a cloned version of this repository using the most current stable release.

Steps: 
- Confirm that the downloaded example works
- Remove the android folder in example/android
- Recreate the Android project using `flutter create -a kotlin .`. (The `-a kotlin` parameter is set by default on newer projects but since you could not reproduce the error, this may make a difference)
- Running the example with the new Kotlin android project does not work as expected

It appears that the type check in [KeyboardVisibilityPlugin.java](https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/android/src/main/java/com/flutter/keyboardvisibility/KeyboardVisibilityPlugin.java) `activity instanceof FlutterActivity` does not return true anymore.

Since it apparently occurred with the switch from Java to Kotlin, migrating the package to Kotlin seemed like a possible fix but did not change the behavior. Instead, using a dynamic type check `Class.forName("io.flutter.embedding.android.FlutterActivity").isInstance(activity)` now works as expected. 

This does only work on a Kotlin android project, though. Support for both variants requires `activity instanceof FlutterActivity || Class.forName("io.flutter.embedding.android.FlutterActivity").isInstance(activity)`.

Since it seems kind of hacky, this may have another cause, but it works a temporary fix for me.

**Comment by MisterJimson** [comment]
Awesome investigation @henk789! Will review and see what can be done.

**Comment by leecommamichael** [comment]
I'm also experiencing this issue, the package that this package forked still works on all platforms. Perhaps AndroidX migration had a regression?

**Comment by MisterJimson** [comment]
Fixed in 0.8.0

**Comment by leecommamichael** [comment]
I have tested and can confirm this is fixed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
